services:
  app:
    build:
      dockerfile: backend/Dockerfile
    container_name: SiriusApp
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  db:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U postgres -d Sirius
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: SiriusNginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  db-data:
    driver: local
  app: