services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: Ai_challenge_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    ports:
      - "80:80"